project:
  type: website

website:
  title: "The Companion book a M1 MODE student should have!"
  navbar:
    left:
      - icon: home
        href: https://marieetienne.github.io/MODE_reproduciblescience/
      - icon: github
        href: https://github.com/MarieEtienne/2024_MODE_OCR
        aria-label: GitHub
      - text: "Instructions"
        href: https://marieetienne.github.io/MODE_reproduciblescience/instructions.html
      - text: "Courses Materials"
        menu:
        - text: Git Intro
          href: https://marieetienne.github.io/reproductibilite/_presentation/english_version.html
        

        
    right:
      - text: Book contente
        menu:
        - text: R simple example 
          href: r_chapter.qmd
        - text: Python simple example 
          href: python_chapter.qmd
        aria-label: GitHub

format:
  html:
    theme: flatly
    linkcolor: "#c0392b"
    fontcolor: "#057174"
    css: styles.css
    toc: true


    
